const DoctorsData = [
  {
    id: 1,
    name: "Dr. Strange",
    degree: "MD (Dietician)",
    specialist:"Dietician",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 10,
  },
  {
    id: 2,
    name: "Dr. ABC",
    degree: "MD (Gynaecologist)",
    specialist:"Gynaecologist",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 8,
  },
  {
    id: 3,
    name: "Dr. XYZ",
    degree: "MBBS",
    specialist:"Dermatology",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 4,
  },
  {
    id: 4,
    name: "Dr. PYQ",
    degree: "MD (Dermatology)",
    specialist:"Dermatology",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 6,
  },
  {
    id: 1,
    name: "Dr. Strange",
    degree: "MD (Dietician)",
    specialist:"Dietician",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 10,
  },
  {
    id: 2,
    name: "Dr. ABC",
    degree: "MD (Gynaecologist)",
    specialist:"Gynaecologist",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 8,
  },
  {
    id: 3,
    name: "Dr. XYZ",
    degree: "MBBS",
    specialist:"Dermatology",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 4,
  },
  {
    id: 4,
    name: "Dr. PYQ",
    degree: "MD (Dermatology)",
    specialist:"Dermatology",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 6,
  },
  {
    id: 1,
    name: "Dr. Strange",
    degree: "MD (Dietician)",
    specialist:"Dietician",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 10,
  },
  {
    id: 2,
    name: "Dr. ABC",
    degree: "MD (Gynaecologist)",
    specialist:"Gynaecologist",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 8,
  },
  {
    id: 3,
    name: "Dr. XYZ",
    degree: "MBBS",
    specialist:"Dermatology",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 4,
  },
  {
    id: 4,
    name: "Dr. PYQ",
    degree: "MD (Dermatology)",
    specialist:"Dermatology",
    imgURL: require("../Assets/doctor.jpg"),
    experience: 6,
  },
];

export default DoctorsData;
