module.exports = [
  {
    key: 1,
    category: "Anxiety",
    specialization: "Andrologist",
    icon: require("../Assets/symptoms/1.png"),
  },
  {
    key: 2,
    category: "Spots on Arms",
    specialization: "Andrologist",
    icon: require("../Assets/symptoms/2.png"),
  },
  {
    key: 3,
    category: "Back Pain",
    specialization: "Andrologist",
    icon: require("../Assets/symptoms/3.png"),
  },
  {
    key: 4,
    category: "Head Injury",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/4.png"),
  },
  {
    key: 5,
    category: "Shakiness",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/5.png"),
  },
  {
    key: 6,
    category: "Diarrhoea",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/6.png"),
  },
  {
    key: 7,
    category: "Vomiting",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/7.png"),
  },
  {
    key: 8,
    category: "Period Cramps",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/8.png"),
  },
  {
    key: 9,
    category: "Blackouts",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/9.png"),
  },
  {
    key: 10,
    category: "Nausea",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/10.png"),
  },
  {
    key: 11,
    category: "Ear pain",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/11.png"),
  },
  {
    key: 12,
    category: "Knuckle Pain",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/12.png"),
  },
  {
    key: 13,
    category: "Eye Swelling",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/13.png"),
  },
  {
    key: 14,
    category: "Eye Vein Swelling",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/14.png"),
  },
  {
    key: 15,
    category: "Watery Eyes",
    specialization: "Dietician",
    icon: require("../Assets/symptoms/15.png"),
  },
  {
    key: 16,
    category: "Eye Itching",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/16.png"),
  },
  {
    key: 17,
    category: "Face Swelling",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/17.png"),
  },
  {
    key: 18,
    category: "Hair Loss",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/18.png"),
  },
  {
    key: 19,
    category: "Shock",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/19.png"),
  },
  {
    key: 20,
    category: "Hypersenstivity",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/20.png"),
  },
  {
    key: 21,
    category: "Sleeplessness",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/21.png"),
  },
  {
    key: 22,
    category: "Itching on Hands",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/22.png"),
  },
  {
    key: 23,
    category: "Bleeding Nose",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/23.png"),
  },
  {
    key: 24,
    category: "Knee Pain",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/24.png"),
  },
  {
    key: 25,
    category: "Itching on Legs",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/25.png"),
  },
  {
    key: 26,
    category: "Pimples",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/26.png"),
  },
  {
    key: 27,
    category: "Face Spots",
    specialization: "Gynaecologist",
    icon: require("../Assets/symptoms/27.png"),
  },
  {
    key: 28,
    category: "Back Acne",
    specialization: "Dermatologist",
    icon: require("../Assets/symptoms/28.png"),
  },
  {
    key: 29,
    category: "Running Nose",
    specialization: "Dermatologist",
    icon: require("../Assets/symptoms/29.png"),
  },
  {
    key: 30,
    category: "Shivering",
    specialization: "Dermatologist",
    icon: require("../Assets/symptoms/30.png"),
  },
];
